/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.7/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.1")
        }
    }
}

gradlePlugin {
    // Define the plugin
    val agpFixer by plugins.creating {
        id = "com.mavenclinic.agp.fixer"
        implementationClass = "com.mavenclinic.gradle.agp.fixer.AgpFixerPlugin"
    }
}

// add a dependency on Guava to force it onto the classpath. Adding this as a dependency in a 
// custom settings plugin seems to resolve https://issuetracker.google.com/issues/330202433 
// while just adding it to the classpath in a buildscript block does not. 
dependencies {
    implementation(libs.guava)
}
